# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField()),
                ('girl_num', models.PositiveIntegerField()),
                ('boy_num', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=256)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
